FROM openjdk:11

RUN mkdir -p /build/install/examples

ADD build/install/examples /build/install/examples

ARG builddate
ENV IMAGE_DATE=$builddate

CMD ["/bin/sleep","inf"]

EXPOSE 8000

################################################
# jove
RUN\
  apt-get update &&\
  apt-get install -y jove &&\
  apt-get clean